# Generated by Django 5.2 on 2025-04-09 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_mapeamento', models.DateField(blank=True, null=True)),
                ('base_dados', models.CharField(blank=True, max_length=100)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_sistema/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('roteiro', models.TextField()),
                ('titulo_padrao', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gerente', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('inicial', 'Inicial'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='inicial', max_length=20)),
                ('documentacao', models.TextField(blank=True)),
                ('atribuido_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuídas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criadas', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistema')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotarefa')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.tarefa')),
            ],
        ),
    ]
