# Generated by Django 5.2 on 2025-04-06 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('roteiro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('prazo', models.DateField()),
                ('link_1', models.URLField(blank=True, null=True)),
                ('link_2', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('inicial', 'Inicial'), ('andamento', 'Em andamento'), ('concluida', 'Concluída')], default='inicial', max_length=20)),
                ('atribuido_para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuídas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criadas', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sistema')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipotarefa')),
            ],
        ),
    ]
