# Generated by Django 5.2 on 2025-04-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='data_ultima_atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
