# Generated by Django 5.2 on 2025-04-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='base_dados',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sistema',
            name='data_mapeamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sistema',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='icones_sistema/'),
        ),
    ]
