# Generated by Django 5.2 on 2025-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotarefa',
            name='checklist',
            field=models.TextField(blank=True, help_text='Um item por linha para formar o checklist.'),
        ),
    ]
