# Generated by Django 5.2 on 2025-04-16 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usou_sistema_externo',
            field=models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default='nao', max_length=3, verbose_name='Usou sistema externo?'),
        ),
        migrations.CreateModel(
            name='TempoSistemaExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_corrido', models.DurationField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ManyToManyField(to='core.sistemaexterno')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempos_externos', to='core.tarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
