# Generated by Django 5.2 on 2025-04-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipotarefa_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipotarefa',
            name='checklist',
        ),
        migrations.CreateModel(
            name='ChecklistSecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='core.tipotarefa')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('obrigatorio', models.BooleanField(default=False)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.checklistsecao')),
            ],
        ),
    ]
