# Generated by Django 5.2 on 2025-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipe_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
