# Generated by Django 5.2 on 2025-04-16 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sistemaexterno_tarefa_usou_sistema_externo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temposistemaexterno',
            name='sistema',
        ),
        migrations.AddField(
            model_name='temposistemaexterno',
            name='sistema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.sistemaexterno'),
            preserve_default=False,
        ),
    ]
