# Generated by Django 5.2 on 2025-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotarefa',
            name='titulo_padrao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
