# Generated by Django 5.2 on 2025-04-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tarefa_documentacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='link_2',
        ),
    ]
