# Generated by Django 5.2 on 2025-04-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_checklistsecao_tipo_delete_checklistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implatacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('implantador', 'Implantador'), ('analista', 'Analista'), ('coordenador', 'Coordenador'), ('gerente', 'Gerente')], default='implantador', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='link_glpi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='link_redmine',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='analista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_analista', to='core.implatacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='implatador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_implantador', to='core.implatacao'),
            preserve_default=False,
        ),
    ]
