# Generated by Django 5.2 on 2025-04-11 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_implatacao_tarefa_link_glpi_tarefa_link_redmine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_analista', to='core.implatacao'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='implatador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_implantador', to='core.implatacao'),
        ),
    ]
