# Generated by Django 5.2 on 2025-04-11 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tarefa_analista_alter_tarefa_implatador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_analista', to='core.implatacao'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='implatador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_implantador', to='core.implatacao'),
        ),
    ]
